version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PRs
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
          - 'aws*'

      babel:
        patterns:
          - '@babel/*'
          - 'babel*'

      hapi:
        patterns:
          - '@hapi/*'
          - 'hapi-*'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'

      pino-logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'
          - 'pino-pretty'

      postgres:
        patterns:
          - 'pg-*'
          - 'pg-copy-streams'
          - 'pg'

      test:
        patterns:
          - '@pact-foundation/*'
          - '@vitest/*'
          - '*vitest*'
          - 'vitest-fetch-mock'

      tools:
        patterns:
          - 'husky'
          - 'nodemon'
          - 'npm-run-all'
          - 'nyc'
          - 'tsx'

      types:
        patterns:
          - '@types/*'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'
      - dependency-name: '@typescript-eslint/*'
      - dependency-name: "@types/node"
        versions: [">=25"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      day: monday
      time: '10:30'
      timezone: 'Europe/London'

    # Delay a PR for a package update by 5 days
    cooldown:
      default-days: 5

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update docker packages
  - package-ecosystem: docker
    directory: /

    ignore:
      - dependency-name: "node"
        versions: [">=25"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      day: monday
      time: '10:30'
      timezone: 'Europe/London'

    # Delay a PR for an action update by 5 days
    cooldown:
      default-days: 5

  # Update docker-compose packages
  - package-ecosystem: docker-compose
    directory: /

    ignore:
      - dependency-name: "node"
        versions: [">=25"]

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      day: monday
      time: '10:30'
      timezone: 'Europe/London'

    # Delay a PR for an action update by 5 days
    cooldown:
      default-days: 5

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      day: monday
      time: '10:30'
      timezone: 'Europe/London'

    # Delay a PR for an action update by 5 days
    cooldown:
      default-days: 5
