services:
  land-grants-backend:
    scale: 0

  land-grants-backend-postgres:
    volumes: !reset []
    tmpfs:
     - /var/lib/postgresql/data

  floci:
    ports:
      - '4566:4566'

volumes:
  postgres_data: null
