# PostGIS with the Ordnance Survey OSTN15 grid installed, without which the
# underlying coordinate transformation software (called PROJ) silently falls
# back to a less accurate way of converting British National Grid to WGS84,
# positioning parcels about a metre from where they should be - see
# docker/proj-data/README.md for more details.

ARG POSTGIS_VERSION=16-3.4

FROM postgis/postgis:${POSTGIS_VERSION}

COPY proj-data/uk_os_OSTN15_NTv2_OSGBtoETRS.tif /usr/share/proj/
