DROP TABLE IF EXISTS moorland_exceptions_tmp CASCADE;

CREATE TEMPORARY TABLE moorland_exceptions_tmp (
  CODICE VARCHAR(10),
    DATA_FINE DATE,
    DATA_INIZIO DATE,
    ID_PARTICELLA INTEGER,
    LADI_ID INTEGER,
    SHAPE_ID INTEGER,
    NGC VARCHAR(50),
    COD_NAZIONALE VARCHAR(10),
    FOGLIO VARCHAR(20),
    PARTICELLA VARCHAR(20),
    AREA_PART NUMERIC(10, 2),
    DATA_INIZIO_VAL DATE,
    DATA_FINE_VAL DATE,
    SHAPE TEXT,
    WKB BYTEA
);
