#!/bin/bash
echo "db update on $POSTGRES_HOST:$POSTGRES_PORT $SCHEMA_NAME as $POSTGRES_USER"

/liquibase/liquibase \
--driver=org.postgresql.Driver \
--changeLogFile=/changelog/db.changelog.xml \
--url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB \
--username="$POSTGRES_USER" --password="$POSTGRES_PASSWORD" --defaultSchemaName="$SCHEMA_NAME" \
rollback v0.0.0
