export const REQUIRED_RULE_DATA = {
  APPLIED_FOR_QUANTITY: 'APPLIED_FOR_QUANTITY',
  AVAILABLE_AREA: 'AVAILABLE_AREA',
  PARCEL_SIZE: 'PARCEL_SIZE',
  AVAILABLE_LENGTH: 'AVAILABLE_LENGTH',
  BOUNDARY_INTERSECTION: 'BOUNDARY_INTERSECTION',
  INTERSECTION: 'INTERSECTION',
  LAND_COVERS: 'LAND_COVERS',
  ACTION_LAND_COVERS: 'ACTION_LAND_COVERS'
}
