CREATE TEMPORARY TABLE land_parcels_tmp (
    geom TEXT,
    ID INTEGER,
    SHEET_ID VARCHAR(10),
    PARCEL_ID VARCHAR(5),
    VALID_FROM TIMESTAMP WITH TIME ZONE,
    VALID_TO TIMESTAMP WITH TIME ZONE,
    GEOM_AREA_SQM NUMERIC(20, 4),
    VERIFIED_ON TIMESTAMP WITH TIME ZONE,
    VERIFICATION_TYPE INTEGER,
    CREATED_ON TIMESTAMP WITH TIME ZONE,
    CREATED_BY VARCHAR(50),
    VALIDATED CHAR(1),
    CENTROID_X NUMERIC(20, 12),
    CENTROID_Y NUMERIC(20, 12),
    LAST_REFRESH_DATE TIMESTAMP WITH TIME ZONE
);
