{
 "title": "land-grants-api (custom)",
 "tags": [
  "custom",
  "service",
  "protected",
  "land-grants-api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Parcels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get Parcels - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "Get Parcels",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/parcels\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "alias": "Get Parcels",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/parcels\" AND NOT url.path:*v2* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Get Parcels",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/parcels\" AND NOT url.path:*v2* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/parcels\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels V2 - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Get Parcels V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/parcels\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels V2 - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "alias": "Get Parcels V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/parcels\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels V2 - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "alias": "Get Parcels V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/parcels\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Parcels V2 - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "alias": "Parcels V2 Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/api/v2/parcels\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Payments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Payment Calculation - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Payment Calculation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/payments/calculate\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment Calculation - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "alias": "Payment Calculation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/payments/calculate\" AND NOT url.path:*v2* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment Calculation - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "Payment Calculation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/payments/calculate\" AND NOT url.path:*v2* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment Calculation - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "alias": "Payment Calculation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/payments/calculate\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Calculate Payment V2 - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "Calculate Payment V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/payments/calculate\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Calculate Payment V2 - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "alias": "Calculate Payment V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/payments/calculate\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Calculate Payment V2 - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "targets": [
    {
     "alias": "Calculate Payment V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/payments/calculate\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Calculate Payment V2 - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "alias": "Payment Calculation V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/api/v2/payments/calculate\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Case Management Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Get Case Management Application - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "Get Case Management Application Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/\" AND NOT url.path:*rerun* AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Case Management Application - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "alias": "Get Case Management Application",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/\" AND NOT url.path:*rerun* AND NOT url.path:*v2* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Case Management Application - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "Get Case Management Application",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/\" AND NOT url.path:*rerun* AND NOT url.path:*v2* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get Case Management Application - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "alias": "Get Case Management Application Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/\" AND NOT url.path:*rerun* AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Re-Run Case Management Application - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "alias": "Re-Run Case Management Application Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/rerun\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Re-Run Case Management Application - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "targets": [
    {
     "alias": "Re-Run Case Management Application",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/rerun\" AND NOT url.path:*v2* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Re-Run Case Management Application - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "alias": "Re-Run Case Management Application",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/rerun\" AND NOT url.path:*v2* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Re-Run Case Management Application - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "targets": [
    {
     "alias": "Re-Run Case Management Application Request",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/case-management-adapter/application/validation-run/rerun\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Application Validate - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "Application Validate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validate\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "alias": "Application Validate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validate\" AND NOT url.path:*v2* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "alias": "Application Validate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validate\" AND NOT url.path:*v2* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "alias": "Application Validate",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/application/validate\" AND NOT url.path:*v2* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate V2 - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "Application Validate V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/application/validate\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate V2 - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "targets": [
    {
     "alias": "Application Validate V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/application/validate\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate V2 - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "targets": [
    {
     "alias": "Application Validate V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/api/v2/application/validate\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validate V2 - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "targets": [
    {
     "alias": "Application Validate V2",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/api/v2/application/validate\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Run - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "targets": [
    {
     "alias": "Application Validation Run",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validation-run/\" AND NOT url.path:*api* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Run - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
   "targets": [
    {
     "alias": "Application Validation Run",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validation-run/\" AND NOT url.path:*api* AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Run - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
   "targets": [
    {
     "alias": "Application Validation Run",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/validation-run/\" AND NOT url.path:*api* AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Run - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
   "targets": [
    {
     "alias": "Application Validation Run",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/application/validation-run/\" AND NOT url.path:*api* AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Runs - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 76 },
   "targets": [
    {
     "alias": "Application Validation Runs",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/*/validation-run\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Runs - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 76 },
   "targets": [
    {
     "alias": "Application Validation Runs",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/*/validation-run\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Runs - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 76 },
   "targets": [
    {
     "alias": "Application Validation Runs",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/application/*/validation-run\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application Validation Runs - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "alias": "Application Validation Runs",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/application/*/validation-run\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Land Data Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Initiate Upload - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 85 },
   "targets": [
    {
     "alias": "Initiate Upload",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/initiate-upload\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initiate Upload - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 85 },
   "targets": [
    {
     "alias": "Initiate Upload",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/initiate-upload\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initiate Upload - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 85 },
   "targets": [
    {
     "alias": "Initiate Upload",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/initiate-upload\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Initiate Upload - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 85 },
   "targets": [
    {
     "alias": "Initiate Upload",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/initiate-upload\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDP Uploader Callback - Count 2xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 93 },
   "targets": [
    {
     "alias": "CDP Uploader Callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/cdp-uploader-callback\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDP Uploader Callback - Count 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 93 },
   "targets": [
    {
     "alias": "CDP Uploader Callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/cdp-uploader-callback\" AND http.response.status_code:[400 TO 499]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDP Uploader Callback - Count 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 93 },
   "targets": [
    {
     "alias": "CDP Uploader Callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "url.path:\"/cdp-uploader-callback\" AND http.response.status_code:[500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CDP Uploader Callback - Resp Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 93 },
   "targets": [
    {
     "alias": "CDP Uploader Callback",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "http.response.response_time", "id": "1", "type": "avg" }
     ],
     "query": "url.path:\"/cdp-uploader-callback\" AND http.response.status_code:[200 TO 299]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Land Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Unlinked Parcels Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "alias": "Unlinked Parcels",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "unlinked_parcels_count", "id": "1", "type": "avg" }
     ],
     "query": "_exists_:unlinked_parcels_count",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unlinked Covers Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "alias": "Unlinked Covers",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "field": "unlinked_covers_count", "id": "1", "type": "avg" }
     ],
     "query": "_exists_:unlinked_covers_count",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}