{
 "title": "land-grants-api (custom)",
 "description": "Application specific metrics",
 "tags": [
  "custom",
  "service",
  "protected",
  "land-grants-api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "500 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "500 errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "http.response.status_code: [500 TO 599]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed Applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Failed Applications",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "message: \"Application validation\" AND \"valid=false\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successful applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Successful Applications",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "message: \"Application validation result\" AND \"valid=true\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "errors",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "container_name: \"land-grants-api\" AND log.level: \"error\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Payment calculation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "Calculation",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "message: \"Payment calculation success\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}