CREATE TEMPORARY TABLE land_covers_tmp (
    geom TEXT,
    SHEET_ID VARCHAR(10),
    PARCEL_ID VARCHAR(5),
    VALID_FROM TIMESTAMP WITH TIME ZONE,
    VALID_TO TIMESTAMP WITH TIME ZONE,
    ID INTEGER,
    REFERENCE_PARCELS_ID INTEGER,
    LAND_COVER_CLASS_CODE INTEGER,
    GEOM_AREA_SQM DECIMAL(20,12),
    VERIFIED_ON TIMESTAMP WITH TIME ZONE,
    VERIFICATION_TYPE VARCHAR(50),
    CREATED_ON TIMESTAMP WITH TIME ZONE,
    CREATED_BY VARCHAR(50),
    LINEAR_FEATURE CHAR(1),
    LAST_REFRESH_DATE TIMESTAMP WITH TIME ZONE
);
