#!/bin/bash

# Validates a pull request title against the commit subject convention.
# Usage: scripts/check-pr-title.sh "<title>" [<author>]

set -e

pr_title="$1"
pr_author="${2:-}"

if [ "$pr_author" = "dependabot[bot]" ]; then
  echo "Dependabot pull request, skipping title check."
  exit 0
fi

# A ticket key, or a revert title generated by GitHub.
pattern='^([A-Z]+-[0-9]+:?[[:space:]]+.+|Revert[[:space:]]+".+")'

if printf '%s' "$pr_title" | grep -qE "$pattern"; then
  echo "Title OK: $pr_title"
  exit 0
fi

echo "PR title '$pr_title' does not match the expected format."
echo ""
echo "Expected:"
echo "  GSPS-123 Short description     the colon is optional"
echo "  GSPS-000 Short description     where there is genuinely no ticket"
echo ""
echo "This repository squashes on merge, so the title becomes the commit"
echo "subject on main. See CONTRIBUTING.md."
exit 1
