#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker compose down
docker compose -f compose.migrate.yml down
docker compose -f compose.migrate.yml run --rm database-up

docker compose \
  -f compose.yml \
  up $@
