#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

npm run setup:husky
# /bin/bash ./scripts/extract-gz-to-sql  src/api/common/migration changelog/
docker compose down
docker compose up -d
