CREATE TABLE land_parcels_tmp (
    geometry_wkt TEXT,
    object_id INTEGER,
    record_id INTEGER,
    sheet_id VARCHAR(10),
    parcel_id INTEGER,
    valid_start TIMESTAMP WITH TIME ZONE,
    valid_end TIMESTAMP WITH TIME ZONE,
    area_sqm DECIMAL(20,4),
    verification_date TIMESTAMP WITH TIME ZONE,
    verification_method INTEGER,
    creation_date TIMESTAMP WITH TIME ZONE,
    created_by_user VARCHAR(50),
    is_validated CHAR(1),
    center_x DECIMAL(20,12),
    center_y DECIMAL(20,12),
    last_updated TIMESTAMP WITH TIME ZONE,
    perimeter_length DECIMAL(20,12),
    calculated_area DECIMAL(20,12)
);