name: Update Package Version

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
  workflow_call:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true
          LATEST_TAG=$(git describe --tags --abbrev=0)

          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git fetch origin "$BRANCH_NAME"
          git checkout "$BRANCH_NAME"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          npm version "$LATEST_TAG" --no-git-tag-version
          git add package.json
          git commit -m "update version [skip ci]" --no-verify
          git push origin "$BRANCH_NAME"
          echo "$LATEST_TAG"